import { useState } from "react";
import { Clock3, FolderOpen, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { openCachedRecentProject, openProjectFile } from "@/features/project/lib/project-file-service";
import { formatRelativeDate } from "@/lib/utils";
import { useProjectStore } from "@/stores/project-store";

export function WelcomeScreen() {
  const recentProjects = useProjectStore((state) => state.recentProjects);
  const removeRecentProject = useProjectStore((state) => state.removeRecentProject);
  const setDialogOpen = useProjectStore((state) => state.setNewProjectDialogOpen);
  const [notice, setNotice] = useState<string | null>(null);
  const openFile = (): void => { void openProjectFile().catch((error: unknown) => setNotice(error instanceof Error ? error.message : "Unable to open the project.")); };
  const openRecent = (projectId: string): void => { try { openCachedRecentProject(projectId); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to open the recent project."); } };
  return <main className="min-h-screen bg-[#101116] text-slate-100"><header className="flex h-14 items-center border-b border-white/10 px-6"><span className="text-base font-semibold tracking-tight text-white">Capa<span className="text-violet-400">Motion</span></span><span className="ml-3 border-l border-white/10 pl-3 text-xs text-slate-500">Roblox animation studio</span></header><section className="mx-auto max-w-4xl px-8 py-20"><p className="text-sm font-medium text-violet-300">WELCOME TO CAPAMOTION</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white">Make motion, one project at a time.</h1><p className="mt-3 max-w-xl text-slate-400">A local-first workspace for building Roblox character animation. Project files use the readable CapaMotion .rma format.</p><div className="mt-8 flex gap-3"><Button onClick={() => setDialogOpen(true)}><Plus size={16} />New project</Button><Button onClick={openFile} variant="secondary"><FolderOpen size={16} />Open project</Button></div>{notice && <p className="mt-4 max-w-2xl rounded-md border border-amber-400/20 bg-amber-400/5 px-3 py-2 text-sm text-amber-100">{notice}</p>}<div className="mt-16"><div className="flex items-center gap-2 text-sm font-medium text-slate-300"><Clock3 size={16} />Recent projects</div><div className="mt-3 divide-y divide-white/8 rounded-xl border border-white/10 bg-white/[0.025]">{recentProjects.length === 0 ? <p className="px-5 py-6 text-sm text-slate-500">Saved projects will appear here.</p> : recentProjects.map((project) => <div className="flex items-center" key={project.id}><button className="flex min-w-0 flex-1 items-center justify-between px-5 py-4 text-left transition-colors hover:bg-white/[0.04]" onClick={() => openRecent(project.id)}><div className="min-w-0"><p className="truncate font-medium text-slate-100">{project.name}</p><p className="mt-1 truncate text-xs text-slate-500">Roblox {project.rigType} - {project.filePath ?? "Local recovery snapshot"}</p></div><span className="ml-4 shrink-0 text-xs text-slate-500">{formatRelativeDate(project.lastOpenedAt ?? project.updatedAt)}</span></button><Button aria-label={`Remove ${project.name} from recent projects`} className="mr-2" onClick={() => removeRecentProject(project.id)} size="sm" variant="ghost"><Trash2 size={14} /></Button></div>)}</div></div></section></main>;
}
